name: venture_app
description: Explore, discover, create - a social community of the daily traveler.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: ^3.0.4
  geocoder: ^0.2.1
  intl: ^0.17.0
  google_maps_flutter: ^2.0.3
  location: ^4.1.1
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  image_picker: ^0.7.5
  cupertino_icons: ^1.0.2
  flutter_google_places: ^0.3.0
  http: ^0.13.3
  path_provider: ^2.0.1
  provider: ^5.0.0
  simple_moment: ^1.1.1
  url_launcher: ^6.0.4
  firebase_storage: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/googlemap_style.txt
    - assets/images/logo.png
    - assets/images/apple-logo.png
    - assets/images/facebook-logo.png
    - assets/images/google-logo.png
    - assets/images/chev-left.png
    - assets/images/bbq-pin-icon.png
    - assets/images/trail-pin-icon.png
    - assets/images/camping-pin-icon.png
    - assets/images/explore_nav_icon.png
    - assets/images/feed_nav_icon.png
    - assets/images/profile_nav_icon.png
    - assets/images/compass_north_icon.png
    - assets/images/compass_center_icon.png
    - assets/images/compass_south_icon.png
    - assets/images/camping_icon.png
    - assets/images/bbq_icon.png
    - assets/images/trail_icon.png
    - assets/images/pin_icon.png
    - assets/images/image_icon.png
    - assets/images/heart_icon.png
    - assets/images/fullheart_icon.png
    - assets/images/comment_icon.png
    - assets/images/comments_icon.png
    - assets/images/bookmark_icon.png
    - assets/images/settings_icon.png
    - assets/images/trash_icon.png
    - assets/images/refresh_icon.png
    - assets/images/options_icon.png
    - assets/images/share_icon.png
    - assets/images/edit_icon.png
    - assets/images/car_icon.png
    - assets/images/notification_icon.png
    - assets/images/power_icon.png
    - assets/images/waze_logo.png
    - assets/images/googlemaps_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Handlee
      fonts:
        - asset: assets/fonts/Handlee-Regular.ttf
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Regular.ttf
        - asset: assets/fonts/Heebo-Thin.ttf
          weight: 100
        - asset: assets/fonts/Heebo-Light.ttf
          weight: 300
        - asset: assets/fonts/Heebo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Heebo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Heebo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Heebo-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
